builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -ldflags=-s -w
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^ci:"
      - "^docs:"
      - "^test:"
